name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: npm install
        run: npm ci

      - name: Run tests
        run: npm test
